### ISSUE TITLE
[20190111] 첫번째 수업 - 오리엔테이션, HTML기초(div)

### ISSUE THREAD

**Issue by HyunSangHan** [HyunSangHan/study-react#1]
**오늘수업**
- ppt로 오리엔테이션
- 알고리즘 - 파이썬 입출력  받아보기
- 웹개발 - HTML의 div 의 기초

다음시간(화)까지
-  파이썬 - view문제 pass시켜보기
- 웹개발 - div로 계산기 화면 만들어오기

**Comment by Yoo-Youngjae** [comment]
궁금한거 생기면 언제든 연락주세요~!
