### ISSUE TITLE
숙제 - 계산기 화면 만들기(HTML Div활용)

### ISSUE THREAD

**Issue by HyunSangHan** [HyunSangHan/study-react#2]
![image](https://user-images.githubusercontent.com/44132406/51069081-7b73a900-166b-11e9-8596-f784ed09759a.png)

숙제 제출합니다.

**일단 div만으로 거의 해서 구역은 딱 넣은 것 같은데, 보완할 부분이 많습니다.**

1. 세로 정렬도 딱 깔끔하게 그 div영역 안에 가운데 정렬이 되면 좋을 것 같다.
   * 찾아보니, table을 만들면 된다, absolute를 사용하면 된다, padding을 넣어라 등등이 있던데 딱 text-align: center; 같은 녀석처럼 깔끔한 놈을 찾지 못했다.

2. 아래 색칠(옅은 회색) 했는데, 네모칸 밖으로 삐져나간다.
    * 딱 네모칸 안까지만 칠하고 싶은데..

3. 높이는 일단 800px을 넣어둬서 대략 눈대중으로 맞추긴 했는데, 가로처럼 한 화면에 꽉채워지게 할 수는 없는 건가? 
    * 아마, 스크롤 때문이겠지?

**소스코드는 이렇습니다 :**

<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <style>
            .same {
                font-size: 42px;
                height: 800px;
            }
            .typing {
                text-align: right;
                height: 12%;
                margin: 5px;
                border: 2px solid #bbbbbb;
            }
            .main {
                margin: 5px;
                height: 80%;
                background-color: #eeeeee
            }
            .flex {
                display: flex;
                height: 18%;
            }
            .first_three {
                width: 75%;
                text-align: center;
                text-color: #ffffff;
                border: 0.2px solid #eeeeee;
                background-color: #dddddd
            }
            .first_one {
                width: 25%;
                border: 0.2px solid #dddddd;
                text-align: center;
            }
            .rest_one {
                width: 25%;
                border: 0.2px solid #dddddd;
                text-align: center;
            }
            .rest_two {
                width: 50%;
                border: 0.2px solid #dddddd;
                text-align: center;
            }
        </style>
    </head>
    <body>
    
    <div class="same">
        <div class="typing"> 0 </div>
        <div class="main">
            <div class="flex">
                <div class="first_three">AC</div>
                <div class="first_one">/</div>
            </div>
    
            <div class="flex">
                <div class="rest_one">7</div>
                <div class="rest_one">8</div>
                <div class="rest_one">9</div>
                <div class="rest_one">*</div>
            </div>
    
            <div class="flex">
                <div class="rest_one">4</div>
                <div class="rest_one">5</div>
                <div class="rest_one">6</div>
                <div class="rest_one">-</div>
            </div>
    
            <div class="flex">
                <div class="rest_one">1</div>
                <div class="rest_one">2</div>
                <div class="rest_one">3</div>
                <div class="rest_one">+</div>
            </div>
    
            <div class="flex">
                <div class="rest_two">0</div>
                <div class="rest_one">.</div>
                <div class="rest_one">=</div>
            </div>
        </div>
    </div>
    </body>
    </html>

일단 view문제부터 풀고, 만약 시간 여유가 좀더 되면 계산기화면도 더 보완해서 다시 올려보겠습니다.

**Comment by Yoo-Youngjae** [comment]
![image](https://user-images.githubusercontent.com/44061214/51111594-d6f69000-183f-11e9-87de-c391f4df8fbf.png)

일단 지난시간 전달한 바는 아주 적었음에도 스스로 이렇게 발전된 코드로 숙제하셔서 수고 많으셨습니다.
텍스트나 배경색 등을 원래 2회 수업때 넣을려 했는데, 불필요하게 되어 참 좋군요..ㅎㅎ
위에서 고민하시는 것들을 적절히 반영하여 코드를 수정해 보았습니다.
바뀐 것중 특징적인 부분은 내일 ppt등을 통해 상세히 설명 드리겠습니다.

**수정한 소스코드는 이렇습니다 :**

<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <style>
        html, body{
            width:100%;
            height:100%;
        }
        .same {
            font-size: 42px;
            /*height: 800px;*/
            height: 100%;
        }
        .typing {
            text-align: right;
            height: 16%;
            margin: 5px;
            padding-right: 10px;
            border: 2px solid #bbbbbb;
            display: flex;
            align-items: center;        /*수직정렬*/
            justify-content: flex-end; /*수평정렬*/
        }
        .main {
            margin: 5px;
            /*height: 80%;*/
            background-color: #eeeeee;
            height: 84%;
        }
        .flex {
            display: flex;
            height: 20%;


        }
        .first_three {
            width: 75%;
            text-align: center;
            text-color: #ffffff;
            border: 0.2px solid #eeeeee;
            background-color: #dddddd;
        }
        .first_one {
            width: 25%;
            border: 0.2px solid #dddddd;
            text-align: center;
        }
        .rest_one {
            width: 25%;
            border: 0.2px solid #dddddd;
            text-align: center;
        }
        .rest_two {
            width: 50%;
            border: 0.2px solid #dddddd;
            text-align: center;
        }
        .flex > div{
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
    </head>
    <body>
    
    <div class="same">
        <div class="typing"> 0 </div>
        <div class="main">
            <div class="flex">
                <div class="first_three">AC</div>
                <div class="first_one">/</div>
            </div>
    
            <div class="flex">
                <div class="rest_one">7</div>
                <div class="rest_one">8</div>
                <div class="rest_one">9</div>
                <div class="rest_one">*</div>
            </div>
    
            <div class="flex">
                <div class="rest_one">4</div>
                <div class="rest_one">5</div>
                <div class="rest_one">6</div>
                <div class="rest_one">-</div>
            </div>
    
            <div class="flex">
                <div class="rest_one">1</div>
                <div class="rest_one">2</div>
                <div class="rest_one">3</div>
                <div class="rest_one">+</div>
            </div>
    
            <div class="flex">
                <div class="rest_two">0</div>
                <div class="rest_one">.</div>
                <div class="rest_one">=</div>
            </div>
        </div>
    </div>
    </body>
    </html>

일단 view문제부터 풀고, 만약 시간 여유가 좀더 되면 계산기화면도 더 보완해서 다시 올려보겠습니다.
