### ISSUE TITLE
숙제 - [SW Expert Academy] view문제(D3)

### ISSUE THREAD

**Issue by HyunSangHan** [HyunSangHan/study-react#3]
숙제 제출합니다.

* 숙제 URL : https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV134DPqAA8CFAYh

10개의 테스트 케이스 중 10개 모두 정답이 나왔는데,
아래와 같이 런타임 오류가 떠서 pass처리를 받지 못했습니다.

![image](https://user-images.githubusercontent.com/44132406/51075461-0639bf80-16cf-11e9-9eb7-f9910a944334.png)

**소스코드는 이렇습니다 :** 

    length = [] # 1
    str_num = [] # 2
    num = [] # 3
    total_score = [] # Final

    for m in range(19):
        length.append(int(input())) # 1
        str_num.append(input().split()) # 2
        num.append([]) # 3
        total_score.append(0) # Final

        def check(m, n):
            tmp = [num[m][n-2], num[m][n-1], num[m][n+1], num[m][n+2]]
            if num[m][n] > max(tmp):
                num_ok = num[m][n] - max(tmp)
            else:
                num_ok = 0
            return num_ok

        for i in range(length[m]): # for change str to int
            num[m].append(int(str_num[m][i]))

        for i in range(2, length[m] - 2):
            total_score[m] += check(m, i)

        print("#{} {}".format(m+1, total_score[m]))

**Comment by Yoo-Youngjae** [comment]
![image](https://user-images.githubusercontent.com/44061214/51114000-5176de00-1847-11e9-954a-a67204852083.png)

거의 다 짜셨는데 메모리 에러가 나왔더군요. 
왜그런지 살펴보니 가장 문제였던 것은 test case가 10개 이므로 for문을 10번 돌려야하는데, 19번을 돌려 발생한 문제였습니다. input이 들어오지 않는데, 프로그램은 계속 돌아 input을 받지 못하고(혹은 잘못 받아지고)  프로그램이 정상종료 되지 못해 어딘가 메모리가 꼬였던 모양입니다.

일단, 19를 10으로 바꾸어도 pass는 나오는데, 그밖에 좀더 효율적인 방향으로 코드를 수정해 보았습니다.

소스코드는 아래와 같습니다.

    def check(n):
        tmp = [num[n - 2], num[n - 1], num[n + 1], num[n + 2]]
        if num[n] > max(tmp):
            num_ok = num[n] - max(tmp)
        else:
            num_ok = 0
        return num_ok
    
    
    num = []        # 3
    total_score = 0 # Final
    for m in range(10):
        length = int(input())     # 1
        str_num = (input().split()) # 2
    
        for i in range(length):      # for change str to int
            num.append(int(str_num[i]))
    
        for i in range(2, length - 2):
            total_score += check(i)
    
        print("#{} {}".format(m+1, total_score))
        #초기화 해주기
        str_num = []    # 2
        num = []        # 3
        total_score = 0  # Final
