### ISSUE TITLE
자습 - [SW Expert Academy] 최빈수 구하기 문제(D2)

### ISSUE THREAD

**Issue by HyunSangHan** [HyunSangHan/study-react#4]
view문제 풀어보고나서, 재밌어서 그 다음 시리즈 하나 더 풀었고 pass받았습니다.

* 문제 URL : https://swexpertacademy.com/main/code/problem/problemDetail.do?contestProbId=AV13zo1KAAACFAYh

**소스코드는 아래와 같습니다. :**

    test_cases = []
    scores_str = []
    scores = []

    all_cases = int(input())

    for i in range(all_cases):
        def check(ss):
            checked = []
            for num in range(0, 100):
                checked.append(0)
            for num in range(0, 100):
                for s in ss:
                    if s == num:
                        checked[num] += 1

            most = max(checked)
            for num in range(0, 100):
                if checked[num] == most:
                    most_num = num        

            return most_num

    #input...
        test_cases.append(int(input()))
        scores_str.append(input().split())
        scores.append([])

        for a in range(len(scores_str[i])-1):   # for change str to int
            scores[i].append(int(scores_str[i][a]))

    #output..
        print("#{} {}".format(test_cases[i], check(scores[i])))

**Comment by Yoo-Youngjae** [comment]
재밌다는 것이 가장 인상적이군요.. 그 무엇보다 막강한 동기부여라 생각합니다. 
위의 코드는 pass하였지만, view에서 수정해야했던 사항 등에 유념하여 다시 코드를 수정해 보는것도 좋은 방법일듯 합니다!

**Comment by HyunSangHan** [comment]
@Yoo-Youngjae 
코드 수정했습니다. 
반복문 안에 불필요한 요소가 있었고, 프린트를 맨 막판에 할 것도 아니면서 괜히 무겁게 리스트에 데이터를 다 들고 있었던 것 같습니다.

**수정한 코드는 :**

    def check(ss):
        checked = []
        for num in range(0, 100):
            checked.append(0)
        for num in range(0, 100):
            for s in ss:
                if s == num:
                    checked[num] += 1
        most = max(checked)
        for num in range(0, 100):
            if checked[num] == most:
                most_num = num                   
        return most_num

    scores_str = []
    scores = []

    all_cases = int(input())

    for i in range(all_cases):
    #input...
        test_case = int(input())
        scores_str.extend(input().split())    
        for a in range(len(scores_str)-1):   # for change str to int
            scores.append(int(scores_str[a]))
    #output..
        print("#{} {}".format(test_case, check(scores)))
    #Initialize..
        scores_str = []
        scores = []

**Comment by Yoo-Youngjae** [comment]
피드백을 바탕으로 스스로 다시 고쳐나가는 속도가 감탄스럽습니다.. 
앞으로 저도 더 빡세게 준비해 봐야겠습니다.
내일 HTML, 알고리즘책 전달해 드리겠습니다. 내일 뵙겠습니다!

**Comment by HyunSangHan** [comment]
**큰 차이는 아니지만, 이게 좀더 깔끔할 것 같아서 또 수정했습니다. :**

    def check(raws):
        checked = []
        for num in range(0, 100):
            checked.append(0)
        for num in range(0, 100):
            for raw in raws:
                if raw == num:
                    checked[num] += 1
        most = max(checked)
        for num in range(0, 100):
            if checked[num] == most:
                most_num = num                   
        return most_num

    all_cases = int(input())

    for i in range(all_cases):
    #Initialize..
        scores = []
        tmp = []
    #input...
        test_case = int(input())
        tmp.extend(input().split())    
        for a in range(len(tmp)):   # for change str to int
            scores.append(int(tmp[a]))
    #output..
        print("#{} {}".format(test_case, check(scores)))
