### ISSUE TITLE
숙제 - 계산기 만들기

### ISSUE THREAD

**Issue by HyunSangHan** [HyunSangHan/study-react#6]
**<숙제>**
0단계 – 0~9까지 버튼구현
1단계 – AC 버튼 구현
2단계 – 더하기 버튼 구현
3단계 – 더하기/빼기 버튼 구현

음... 일단 3단계까지 모두 완성한 '척'은 해봤는데, 2%부족합니다.(누구나 인식할 수 있는, 꽤 치명적인 오류..)
* 그럼, 4단계는 . 이겠죠? 이건 아직 고민할 시간이 부족했어서, 하지 못했습니다.

**현재까지의 코드(js만 첨부)는 아래와 같고, 내일 코드리뷰가 필요하겠습니다. :**

    import React, { Component } from 'react';
    // import logo from './logo.svg';
    import './App.css';
    
    class App extends Component {
    
      constructor(props){
        super(props);
        this.state = {
          value : 0,
          tmp_value_1 : 0,
          tmp_value_2 : 0,
          tmp_oper : false
        }
      }
    
      clickNum = (num) => () => {
        if(this.state.tmp_oper === false) {
          if (this.state.value < Math.pow(2, 49)) {
            this.setState({
              value: this.state.value * 10 + num
            });
          } else {
            this.setState({
              value: this.state.value
            });
          }
        } else {
            this.setState({
              value: this.state.tmp_value_2 * 10 + num,
              tmp_value_2: this.state.value
            });
          }
        }
    
      refreshValue = () => () => {
        this.setState({
          value: 0
        });
      }
    
      clickOper = (oper) => () => { 
        this.setState({
          tmp_value_1: this.state.value,
          tmp_oper: oper,
        });
        this.calculateOper(); // maybe..need parameter?
      }
    
      calculateOper = () => () => {
        if(this.state.tmp_oper === '+') {
          this.setState({
            value: this.state.tmp_value_1 + this.state.value
          });
        } else if(this.state.tmp_oper === '*') {
          this.setState({
            value: this.state.tmp_value_1 * this.state.value
          });
        } else if(this.state.tmp_oper === '-') {
          this.setState({
            value: this.state.tmp_value_1 - this.state.value
          });
        } else if(this.state.tmp_oper === '/') {
          this.setState({
            value: this.state.tmp_value_1 / this.state.value
          });
        }
        // else if(this.state.tmp_oper === '.') {
        //   this.setState({
        //    ////////////have to write
        //   });
        // }
      }
    
      render() {
        return (
            <div className="App">
    
              <div className="same">
                <div className="typing"> {this.state.value}</div>
                <div className="main">
                  <div className="flex">
                    <div onClick={this.refreshValue()} className="first_three">AC</div>
                    <div onClick={this.clickOper("/")} className="first_one">/</div>
                  </div>
    
                  <div className="flex">
                    <div onClick={this.clickNum(7)} className="rest_one">7</div>
                    <div onClick={this.clickNum(8)} className="rest_one">8</div>
                    <div onClick={this.clickNum(9)} className="rest_one">9</div>
                    <div onClick={this.clickOper("*")} className="rest_one">*</div>
                  </div>
    
                  <div className="flex">
                    <div onClick={this.clickNum(4)} className="rest_one">4</div>
                    <div onClick={this.clickNum(5)} className="rest_one">5</div>
                    <div onClick={this.clickNum(6)} className="rest_one">6</div>
                    <div onClick={this.clickOper("-")} className="rest_one">-</div>
                  </div>
    
                  <div className="flex">
                    <div onClick={this.clickNum(1)} className="rest_one">1</div>
                    <div onClick={this.clickNum(2)} className="rest_one">2</div>
                    <div onClick={this.clickNum(3)} className="rest_one">3</div>
                    <div onClick={this.clickOper("+")} className="rest_one">+</div>
                  </div>
    
                  <div className="flex">
                    <div onClick={this.clickNum(0)} className="rest_two">0</div>
                    <div className="rest_one">.</div>
                    <div onClick={this.calculateOper()} className="rest_one">=</div>
                  </div>
                </div>
              </div>
    
            </div>
        );
      }
    }
    
    export default App;

**Comment by HyunSangHan** [comment]
이 정도면 더하기, 곱하기에서 문제는 없어 보이고, 다만 빼기와 나누기에서 약간의 이슈가 있습니다.
일단 좀더 수정한 코드 업로드합니다.

**js파일 소스코드 :**

    import React, { Component } from 'react';
    // import logo from './logo.svg';
    import './App.css';
  
    class App extends Component {
  
      constructor(props){
        super(props);
        this.state = {
          value : 0,
          tmp_value_1 : 0,
          tmp_value_2 : 0,
          tmp_oper : false
        }
      }
  
      clickNum = (num) => () => {
        if(this.state.tmp_oper === false) {
          if (this.state.value < Math.pow(2, 49)) {
            this.setState({
              value: this.state.value * 10 + num
            });
          } else {
            this.setState({
              value: this.state.value
            });
          }
        } else {
            this.setState({
              value: this.state.tmp_value_2 * 10 + num,
              tmp_value_2: this.state.tmp_value_2 * 10 + num
            });
          }
        }
  
      refreshValue = () => () => {
        this.setState({
          value: 0,
          tmp_value_1: 0,
          tmp_value_2: 0
        });
      }
  
      clickOper = (oper) => () => {
        this.setState({
          tmp_value_1: this.state.value,
          tmp_value_2: 0,
          tmp_oper: oper
        });
        this.calculateOper();
      }
  
      calculateOper = () => () => {
        if(this.state.tmp_oper === '+') {
          this.setState({
            value: this.state.tmp_value_1 + this.state.value
          });
        } else if(this.state.tmp_oper === '*') {
          this.setState({
            value: this.state.tmp_value_1 * this.state.value
          });
        } else if(this.state.tmp_oper === '-') {
          this.setState({
            value: this.state.tmp_value_1 - this.state.value
          });
        } else if(this.state.tmp_oper === '/') {
          this.setState({
            value: this.state.tmp_value_1 / this.state.value
          });
        }
        // else if(this.state.tmp_oper === '.') {
        //   this.setState({
        //    ////////////have to write
        //   });
        // }
        this.setState({
          tmp_value_1: this.state.tmp_value_2
    //      tmp_oper: oper
        });
      }
  
      render() {
        return (
            <div className="App">
  
              <div className="same">
                <div className="typing"> {this.state.value}</div>
                <div className="main">
                  <div className="flex">
                    <div onClick={this.refreshValue()} className="first_three">AC</div>
                    <div onClick={this.clickOper("/")} className="first_one">/</div>
                  </div>
  
                  <div className="flex">
                    <div onClick={this.clickNum(7)} className="rest_one">7</div>
                    <div onClick={this.clickNum(8)} className="rest_one">8</div>
                    <div onClick={this.clickNum(9)} className="rest_one">9</div>
                    <div onClick={this.clickOper("*")} className="rest_one">*</div>
                  </div>
  
                  <div className="flex">
                    <div onClick={this.clickNum(4)} className="rest_one">4</div>
                    <div onClick={this.clickNum(5)} className="rest_one">5</div>
                    <div onClick={this.clickNum(6)} className="rest_one">6</div>
                    <div onClick={this.clickOper("-")} className="rest_one">-</div>
                  </div>
  
                  <div className="flex">
                    <div onClick={this.clickNum(1)} className="rest_one">1</div>
                    <div onClick={this.clickNum(2)} className="rest_one">2</div>
                    <div onClick={this.clickNum(3)} className="rest_one">3</div>
                    <div onClick={this.clickOper("+")} className="rest_one">+</div>
                  </div>
  
                  <div className="flex">
                    <div onClick={this.clickNum(0)} className="rest_two">0</div>
                    <div className="rest_one">.</div>
                    <div onClick={this.calculateOper()} className="rest_one">=</div>
                  </div>
                </div>
              </div>
  
            </div>
        );
      }
    }
  
    export default App;


**css파일 소스코드 :**

    .App {
      text-align: center;
    }
  
    .App-logo {
      animation: App-logo-spin infinite 20s linear;
      height: 40vmin;
    }
    
    .App-header {
      background-color: #282c34;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      font-size: calc(10px + 2vmin);
      color: white;
    }
  
    .App-link {
      color: #61dafb;
    }
  
    @keyframes App-logo-spin {
      from {
        transform: rotate(0deg);
      }
      to {
        transform: rotate(360deg);
      }
    }
  
    html, body {
      width: 100%;
      height: 100%;
    }
  
    .same {
      font-size: 20px;
      height: 100%; /*왜안될까............. 100%녀석이 */
    }
    .typing {
      text-align: right;
      height: 16%;
      margin: 5px;
      border: 2px solid #bbbbbb;
    }
    .main {
      margin: 5px;
      height: 84%;
      background-color: #eeeeee
    }
    .flex {
      display: flex;
      height: 100%;
    }
  
    .flex > div {
      display: flex;
      justify-content: center;
      align-items: center;
    }
  
    .flex > div:hover {
      background-color: antiquewhite;
      cursor: pointer;
    }
  
    .first_three {
      width: 75%;
      text-align: center;
      text-color: #ffffff;
      border: 0.2px solid #eeeeee;
      background-color: #dddddd
    }
    .first_one {
      width: 25%;
      border: 0.2px solid #dddddd;
      text-align: center;
    }
    .rest_one {
      width: 25%;
      border: 0.2px solid #dddddd;
      text-align: center;
    }
    .rest_two {
      width: 50%;
      border: 0.2px solid #dddddd;
      text-align: center;
    }

[추가질문] css파일에서,
html, body과 .same 모두 height 100% 지정했는데 왜 생각대로 안되는지 모르겠습니다.

**Comment by Yoo-Youngjae** [comment]
점심먹고 잠시 보았는데, 코드에 대한 리뷰는 저녁에 세미나 시간에 함께 고쳐나가는 식으로 하는게 적절할듯 합니다. css와 javascript 모두를 같이 고쳐보고, 어느정도 준비한 디버깅 및 자바스크립트 코딩 방법 등을 ppt로 전달 드리겠습니다.

**Comment by HyunSangHan** [comment]
완성은 일단 했는데, 어려웠던 부분이 있습니다.

1. HTML / CSS가 이젠 더 어렵게 느껴짐... 좀더 빠삭하게 알 필요가 있겠음
2. 자료형에 대한 문제 같은데.. 0.1을 n제곱할 때 숫자에서 약간의 차이가 납니다. float이기 때문인가요? 해결책도 궁금합니다.
3. 숫자가 어느 일정 선 이상 커지면 더이상 숫자를 입력하지 못하게 하는 기능은, 언뜻 생각하기엔 쉬운데 완벽히 넣으려고 섬세하게 짜면 오히려 코드가 꼬이기 시작합니다. 

일단 아래와 같이 계산기 마무리했고, js파일과 css파일 모두 push해뒀습니다.
1월 21일의 1번째 commit한 파일입니다.

**소스코드는(엄청 깁니다.) :** 

    import React, { Component } from 'react';
    // import logo from './logo.svg';
    import './App.css';
    
    class App extends Component {
    
      constructor(props){
        super(props);
        this.state = {
          operator: false,
          is_overlapped: false,
          is_first_num: true,
          is_float: false,
          num_saved: 0, // (1st number or total number)
          num_displayed: 0, // (2st number)
          num_under_point: 0, // (float number)
          is_under_first_num: true,
          num_pow: 0,
          shadow: " "
        }
      }
    
      clickNum = (num) => () => {
        let is_overlapped = this.state.is_overlapped;
        let operator = this.state.operator;
        let num_displayed = this.state.num_displayed;
        let is_first_num = this.state.is_first_num;
        let num_saved = this.state.num_saved;
        let is_float = this.state.is_float;
        let num_under_point = this.state.num_under_point;
        let is_under_first_num = this.state.is_under_first_num;
        let num_pow = this.state.num_pow;
        let shadow = this.state.shadow;
    
        let exp;
    
    
          //for 소수점 위//
          if (is_float === false) {
            if (operator === false) {
              if (is_first_num === true) { // [CASE 1] 연산자: 없음, 첫번째 숫자타이핑: Y
                is_first_num = false;
                num_displayed = num;
              } else { // [CASE 2] 연산자: 없음, 첫번째 숫자: N
                num_displayed = num_displayed * 10 + num;
              }
            } else {
              if (is_first_num === true) { // [CASE 3] 연산자: 있음, 첫번째 숫자타이핑: Y
                is_overlapped = false;
                if (num_displayed !== "무한대") {
                  num_saved = num_displayed;
                }
                num_displayed = num;
                is_first_num = false;
              } else { // [CASE 4] 연산자: 있음, 첫번째 숫자타이핑: N
                num_displayed = num_displayed * 10 + num;
              }
            }
          }
    
    
          //for 소수점 아래//
          else {
            num_pow += 1; //몇번째 소수점인지에 대한 숫자.
            exp = Math.pow(0.1, num_pow);
    
            if (operator === false) {
              if (is_under_first_num === true) { // [CASE 1] 연산자: 없음, 첫번째 소수 타이핑: Y
                is_under_first_num = false;
                num_under_point = num * exp;
                num_displayed = num_displayed + num_under_point;
              } else { // [CASE 2] 연산자: 없음, 첫번째 소수 타이핑: N
                num_under_point = num * exp;
                num_displayed = num_displayed + num_under_point;
              }
            } else {
              if (is_under_first_num === true) { // [CASE 3] 연산자: 있음, 첫번째 소수 타이핑: Y
                is_under_first_num = false;
                is_overlapped = false;
                num_under_point = num * exp;
                num_displayed = num_displayed + num_under_point;
              } else { // [CASE 4] 연산자: 있음, 첫번째 소수 타이핑: N
                num_under_point = num * exp;
                num_displayed = num_displayed + num_under_point;
              }
            }
    
    
    //      num_displayed = num_displayed.toFixed(num_pow);
          }
    
          if(operator === false) {
            shadow = " ";
          } else {
            shadow = num_saved + " " + operator;
          }
    
        this.setState({
          is_overlapped: is_overlapped,
          operator: operator,
          num_displayed: num_displayed,
          is_first_num: is_first_num,
          num_saved: num_saved,
          is_float: is_float,
          num_under_point: num_under_point,
          is_under_first_num: is_under_first_num,
          num_pow: num_pow,
          shadow: shadow
        });
      }
    
      refreshValue = () => () => {
        this.setState({
          operator: false,
          is_overlapped: false,
          is_first_num: true,
          num_saved: 0,
          num_displayed: 0,
          is_float: false,
          num_under_point: 0,
          is_under_first_num: true,
          num_pow: 0,
          shadow: " "
        });
      }
    
      clickOper = (oper) => () => {
        let is_overlapped = this.state.is_overlapped;
        let operator = this.state.operator;
        let num_saved = this.state.num_saved;
        let num_displayed = this.state.num_displayed;
        let is_first_num = this.state.is_first_num;
        let is_float = this.state.is_float;
        let num_pow = this.state.num_pow;
        let num_under_point = this.state.num_under_point;
        let shadow = this.state.shadow;
    
    
        //  숫자 너무 크면 고정시키는 코드 넣어야함
    
        if (is_overlapped === false) {
          shadow = " ";
          if (operator === '+') { //중복이 아닌, 첫번째 연산자 입력일 경우
            num_saved = num_saved + num_displayed;
            num_displayed = num_saved;
          } else if (operator === '-') {
            num_saved = num_saved - num_displayed;
            num_displayed = num_saved;
          } else if (operator === '*') {
            num_saved = num_saved * num_displayed;
            num_displayed = num_saved;
          } else if (operator === '/') {
            if(num_displayed === 0) {
              shadow = num_saved + " " + operator;
              num_displayed = "무한대";
            } else {
              num_saved = num_saved / num_displayed;
              num_displayed = num_saved;
    
            }
          }
        }
    
        is_first_num = true;
        is_overlapped = true;
    
        if (oper !== '=') {
          operator = oper;
          is_float = false;
          num_pow = 0;
          num_under_point = 0;
        }
    
    
        this.setState({
          is_overlapped: is_overlapped,
          operator: operator,
          num_saved: num_saved,
          num_displayed: num_displayed,
          is_first_num: is_first_num,
          is_float: is_float,
          num_pow: num_pow,
          num_under_point: num_under_point,
          shadow: shadow
        });
    
    
      }
    
    
    
      clickPoint = () => () => {
        let is_float = this.state.is_float;
    
        is_float = true;
    
        this.setState({
          is_float: is_float
        });
      }
    
    
      render() {
        return (
            <div className="App">
    
              <div className="same">
                <div className="typingtool">
                  <div className="flex_typingtool">
                    <div className="shadow_typing">
                      {this.state.shadow}
                    </div>
                    <div className="typing">
                      {this.state.num_displayed}
                    </div>
                  </div>
                </div>
    
                <div className="caltool">
                  <div className="flex_cartool">
                    <div onClick={this.refreshValue()} className="first_three">AC</div>
                    <div onClick={this.clickOper("/")} className="first_one">/</div>
                  </div>
    
                  <div className="flex_cartool">
                    <div onClick={this.clickNum(7)} className="rest_one">7</div>
                    <div onClick={this.clickNum(8)} className="rest_one">8</div>
                    <div onClick={this.clickNum(9)} className="rest_one">9</div>
                    <div onClick={this.clickOper("*")} className="rest_one">*</div>
                  </div>
    
                  <div className="flex_cartool">
                    <div onClick={this.clickNum(4)} className="rest_one">4</div>
                    <div onClick={this.clickNum(5)} className="rest_one">5</div>
                    <div onClick={this.clickNum(6)} className="rest_one">6</div>
                    <div onClick={this.clickOper("-")} className="rest_one">-</div>
                  </div>
    
                  <div className="flex_cartool">
                    <div onClick={this.clickNum(1)} className="rest_one">1</div>
                    <div onClick={this.clickNum(2)} className="rest_one">2</div>
                    <div onClick={this.clickNum(3)} className="rest_one">3</div>
                    <div onClick={this.clickOper("+")} className="rest_one">+</div>
                  </div>
    
                  <div className="flex_cartool">
                    <div onClick={this.clickNum(0)} className="rest_two">0</div>
                    <div onClick={this.clickPoint()} className="rest_one">.</div>
                    <div onClick={this.clickOper("=")} className="rest_one">=</div>
                  </div>
                </div>
              </div>
    
            </div>
        );
      }
    }
    
    export default App;

**Comment by HyunSangHan** [comment]
최종 산출물 - http://calculator.dothome.co.kr/
